name: zynkup
description: "Zynkup â€” Campus Event App | MAIT Tech Fest 2025"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.13.0

  # Google Sign-In
  google_sign_in: ^6.1.6

  # Date & Time
  intl: ^0.18.0

  # UI & Icons
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png